name: lint
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install pnpm
              run: npm i -g pnpm

            - name: Install deps
              run: pnpm i

            - name: Run ESLint
              run: pnpm run lint
